# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pageID',
            field=models.CharField(default='001', max_length=10),
        ),
    ]
